### ISSUE TITLE
General Brainstorming

### ISSUE THREAD

**Issue by rubywerman** [stellaw1/fellow-crossing#1]
Things to flesh out:
- [x] What's the goal of the game? How do you "win?"
- [x] What activities can you do?
- [x] What different rooms?

**Comment by rubywerman** [comment]
Activities: chat with other players, walk around, customize office/character
Places on maps: break room, home office

**Comment by stellaw1** [comment]
Tasks: 
 - networking 
 - map layout
 - customizing characters
 - static office layout (eventually want customizable design)
 - assets
 - database for storing user name (start with just storing user's names eventually want password authentication)
 - chat feature (eventually want video calling feature)

**Comment by stellaw1** [comment]
Initial research: 
 - Kanav: networking & chat features
 - Stella: deployment (web hosted or native app) & customization of characters and office
 - Ruby: assets, animation & design/ layout
 - Nabanita: database (storing user data and usernames)
