### ISSUE TITLE
Research:  database for storing user data

### ISSUE THREAD

**Issue by stellaw1** [stellaw1/fellow-crossing#5]
### Questions: 
 - what database are we going to use to store user data such as usernames, customizations, location, etc
 - how are we going to integrate the database with our network and game client

### Potential solutions:
 -  Heroku + FireBase

**Comment by dnabanita7** [comment]
1) According to [this discussion](https://forum.unity.com/threads/best-way-to-handle-a-database-for-rpg-game.191468/) and [this](https://gamedev.stackexchange.com/questions/2282/what-kind-of-databases-are-usually-used-in-an-mmorpg) I started looking up at XML sources.
2) https://www.vertabelo.com/blog/mmo-games-and-database-design/
3) https://github.com/jgoodman/MySQL-RPG-Schema (a template which will be helpful)
4) DB for a simple RPG : https://stackoverflow.com/questions/48051507/database-table-structure-for-a-simple-rpg

**Comment by dnabanita7** [comment]
I will use Amazon RDS for creating a DB instance https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Tutorials.WebServerDB.CreateDBInstance.html

**Comment by dnabanita7** [comment]
I got a really good GDScript sqlite wrapper i.e. https://github.com/khairul169/gdsqlite
